### ISSUE TITLE
select-layout plugin active then tabular page items not added on cart.

### ISSUE THREAD

**Issue by vijayvp710** [kathyisawesome/wc-mnm-select-layout#1]
Hello  @helgatheviking 

Cart item not added because of "WooCommerce Mix and Match: Select Layout" plugin. I am checked if select layout plugin is disable then add to cart items working fine in tabular mode.

I found "You have selected too few items. Please choose 3 items for" error and not adding sub items in cart.
I have set default wordpress theme and disable all other plugins but still not work.
Can you please check and let me know. Because I have really urgent for this issue.

![image](https://user-images.githubusercontent.com/29775116/119222321-62b80f80-bb11-11eb-91d2-7fada0d3896c.png)

This is happening to products that are not using the select layout.

Thanks 
Vijay Prajapati.

**Comment by helgatheviking** [comment]
Thanks @vijayvp710 for reporting this. So this is happening while the select layout plugin is active. Can you confirm if the product in question is using the select layout? Or this is happening to products that are _not_ using the select layout?

Please keep in mind that these mini-extensions are provided "as is" and are worked on as availability permits. 

Though I have a suspicion that we need to conditionally check that the product is using the select layout here:
https://github.com/kathyisawesome/wc-mnm-select-layout/blob/master/wc-mnm-select-layout.php#L232

**Comment by helgatheviking** [comment]
Can you try updating to the latest `master` and see if that resolves it? That's the best I'm able to do for a while.

**Comment by vijayvp710** [comment]
@helgatheviking 

I have updated the issue is happening to products that are not using the select layout.

Thanks it's working fine.
